#!/bin/sh

set -e

#VARS
SWING_FILE_OPENJDK21="/etc/java-21-openjdk/swing.properties"
SWING_FILE_LLIUREX="/usr/share/lliurex-java-panel/swing.properties"
PACKAGE_NAME="lliurex-java-panel"

case "$1" in
   configure)
		if [ -f $SWING_FILE_OPENJDK8 ];then
			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${SWING_FILE_OPENJDK21}.diverted ${SWING_FILE_OPENJDK21} ; then
				ln -fs ${SWING_FILE_LLIUREX} ${SWING_FILE_OPENJDK8}
   			else
   				echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
			fi
		fi	

      newVersion=$(dpkg-query --showformat='${Version}' --show lliurex-java-panel)
      tokenDir=/var/lib/lliurex-java-panel/version
      echo "$newVersion" > "$tokenDir" || true
   				
   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#
