#!/bin/sh

set -e

#VARS
 ="/etc/java-8-openjdk/swing.properties"
SWING_FILE_LLIUREX="/usr/share/lliurex-java-panel/swing.properties"
PACKAGE_NAME="lliurex-java-panel"

case "$1" in
   configure)
		if [ -f $SWING_FILE_OPENJDK8 ];then
			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${SWING_FILE_OPENJDK8}.diverted ${SWING_FILE_OPENJDK8} ; then
				ln -fs ${SWING_FILE_LLIUREX} ${SWING_FILE_OPENJDK8}
   			else
   				echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
			fi
		fi	
   				
   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#
